  <% require "uri" %>

  db_config: &db_config
               username: postgres
               password: 'liferay'
               adapter: postgresql
               encoding: unicode
               pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
               timeout: 5000
               host: <%= ENV['IP'] %>

  development:
    <<: *db_config
    database: muvy_development

  test:
    <<: *db_config
    database: muvy_test

  production:
    <<: *db_config
    database: muvy_production
